### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by kovach-dmitry** [OS-IS/ai202-kovach#1]

**Comment by kovach-dmitry** [comment]
Було виконано клонування GitHub-репозиторію на локальний комп`ютер без використання процесу автентифікації. У результаті було показано, що репозиторій вже було створено на комп'ютері.
![1](https://github.com/user-attachments/assets/24804ea3-5dc8-4693-bbc7-4b1460fffd69)

**Comment by kovach-dmitry** [comment]
Оновлення GitHub-репозиторій зі змінами з локального Git-репозиторія, використовуючи Token.
![2](https://github.com/user-attachments/assets/cfde1f11-1e37-47fc-b14e-0e9d007304c7)

**Comment by kovach-dmitry** [comment]
Створення SSH-ключів.
![3](https://github.com/user-attachments/assets/c86c0303-2e63-4253-a10d-e08516ace699)

**Comment by kovach-dmitry** [comment]
Клонування GitHub-репозиторій на локальний комп`ютер з використанням SSH-ключів.
![4](https://github.com/user-attachments/assets/931c8788-9d7a-4044-87e8-1736e2826558)

**Comment by oleksandrblazhko** [comment]
Треба зробити Pull Request

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 5 балів.
Дякую
