### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai202-kovach#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
4) Відомо, що з серпня 2021 року GitHub-сервер замінив класичний процес 
аутентифікації через пароль на процес з використанням Token 
під час безпечного оновлення GitHub-репозиторію. 
Поясніть, будь ласка, чому так було зроблено?

**Comment by kovach-dmitry** [comment]
Заміну аутентифікації через пароль на процес з використанням Token було зроблено для підвищення безпеку користувачів і зменшити ризик несанкціонованого доступу до репозиторіїв. Основна суть змін полягала у тому, що паролі є вразливими до атак типу фішинг або brute-force, і тому паролі не вважаються достатньо надійними.
Персональні токени доступу надають більш безпечну альтернативу, оскільки вони можуть бути налаштовані з обмеженими дозволами і легко відкликані в разі потреби.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
